### ISSUE TITLE
Crash when directory doesn't exist

### ISSUE THREAD

**Issue by 132ikl** [john01dav/mbs#2]
Steps to reproduce:
1. Create a .yml for mbs without creating module directories
2. Try to use mbs with the .yml

What I expected:
Should exit cleanly, ie. "Cannot find directory /path/to/dir" and point user to USAGE.md

What actually happened:
```terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: recursive directory iterator cannot open directory: No such file or directory [./modules/module1/include]
```

**Comment by john01dav** [comment]
This is not a bug, it's a feature. Specifically, MBS's intended method of showing errors is to show an exception. I figured this would be ideal because it is intended for C and C++ developers who are probably perfectly capable of reading such an error, and because it decreases code complexity, making maintenance and pull requests easier.
